apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    # REEMPLAZA ESTA URL POR LA URL DE TU REPOSITORIO GIT
    repoURL: 'https://github.com/cps20/argocd-test-app'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
